<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About this add-on' => '@@Acerca de este add-on@@',
    'Active' => 'Activo',
    'Add-ons' => 'Add-ons',
    'Anonymize Ip' => 'Volver IP Anónima',
    'Are you sure you want to delete these tracking configurations? All data related to each item will be deleted. This action cannot be undone.' => '¿Está seguro que desea eliminar estas configuraciones de rastreo? Todos los datos relacionados con cada elemento serán eliminados. Esta acción no puede deshacerse.',
    'Are you sure you want to delete this tracking configuration? All data related to this item will be deleted. This action cannot be undone.' => '¿Está seguro que desea eliminar esta configuración de rastreo? Todos los datos relacionados con este elemento serán eliminados. Esta acción no puede deshacerse.',
    'Create' => 'Crear',
    'Create Form Tracking' => 'Crear Seguimiento de Formulario',
    'Delete' => 'Eliminar',
    'Form' => 'Formulario',
    'Form Tracking' => 'Seguimiento de Formulario',
    'Google Analytics' => 'Google Analytics',
    'ID' => 'ID',
    'Inactive' => 'Inactivo',
    'OFF' => 'OF',
    'ON' => 'ON',
    'Page not found.' => 'Página no encontrada.',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Select a form...' => 'Seleccionar un formulario...',
    'Start Tracking!' => 'Empezar a rastrear!',
    'Status' => 'Estado',
    'The form tracking has been successfully created.' => 'El seguimiento del formulario se ha creado de forma exitosa',
    'The form tracking has been successfully deleted.' => 'El seguimiento del formulario se ha creado de forma exitosa',
    'The form tracking has been successfully updated.' => 'El seguimiento del formulario se ha creado de forma exitosa',
    'The selected items have been successfully deleted.' => 'Los elementos seleccionados se han eliminado de forma exitosa.',
    'The selected items have been successfully updated.' => 'Los elementos seleccionados se han actualizado de forma exitosa.',
    'Tracking Domain' => 'Dominio a Rastrear',
    'Tracking ID' => 'ID de Rastreo',
    'Update' => 'Actualizar',
    'Update Form Tracking' => 'Actualizar Seguimiento de Formulario',
    'Update Status' => 'Actualizar estado',
    'View' => 'Vista',
    'View Record' => 'Ver Registro',
    'With this add-on, Google Analytics will be added directly to your form to track successful submissions and provide more insights on your form\'s performance.' => 'Con este add-on, Google Analytics será añadido directamente a tu formulario para realizar un seguimiento de los envíos y proveer más insights sobre el rendimiento de tus formularios.',
];
