<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back up your database.' => '',
    'Backup your files.' => '',
    'Choose language' => '',
    'Congratulations, you have updated Easy Forms!' => '',
    'Continue' => '',
    'Finished' => '',
    'For security reasons, you must comment again the uncommented line in the "config/web.php" file.' => '',
    'Go to Easy Forms' => '',
    'If you have performed the next steps, you may proceed to update Easy Forms.' => '',
    'Install your new files in the right location, as described in the documentation.' => '',
    'Next Step' => '',
    'Note: If you have problems running your site, get in touch with our support team and we will be more than happy to help you.' => '',
    'Requirements' => '',
    'Save and continue' => '',
    'There was an error updating your database, please contact us.' => '',
    'Update app' => '',
    'Update to Easy Forms {version}' => '',
    'Updating Easy Forms' => '',
    'You have successfully updated your Easy Forms application.' => '',
    'Your application was successfully updated!' => '',
];
