<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A WebHook is just a push notification from us to another server every time someone submits a form.' => '',
    'Active' => '',
    'Add-ons' => '',
    'Are you sure you want to delete these webhooks? All data related to each item will be deleted. This action cannot be undone.' => '',
    'Are you sure you want to delete this webhook? All data related to this item will be deleted. This action cannot be undone.' => '',
    'Create' => '',
    'Create Webhook' => '',
    'Create a WebHook' => '',
    'Delete' => '',
    'Form' => '',
    'Handshake Key' => '',
    'ID' => '',
    'Inactive' => '',
    'Json' => '',
    'OFF' => '',
    'ON' => '',
    'Page not found.' => '',
    'Reset' => '',
    'Search' => '',
    'Select a form...' => '',
    'Send notifications to another server' => '',
    'Status' => '',
    'The selected items have been successfully deleted.' => '',
    'The selected items have been successfully updated.' => '',
    'The webhook has been successfully created.' => '',
    'The webhook has been successfully deleted.' => '',
    'The webhook has been successfully updated.' => '',
    'Update' => '',
    'Update Status' => '',
    'Update Webhook' => '',
    'Url' => '',
    'View Record' => '',
    'Webhook' => '',
    'Webhooks' => '',
    'Your handshake key' => '',
    'Your web hook url' => '',
];
