<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Add-ons' => '',
    'Anonymize Ip' => '',
    'Are you sure you want to delete these tracking configurations? All data related to each item will be deleted. This action cannot be undone.' => '',
    'Are you sure you want to delete this tracking configuration? All data related to this item will be deleted. This action cannot be undone.' => '',
    'Create' => '',
    'Create Form Tracking' => '',
    'Delete' => '',
    'Form' => '',
    'Form Tracking' => '',
    'Google Analytics' => '',
    'ID' => '',
    'Inactive' => '',
    'OFF' => '',
    'ON' => '',
    'Page not found.' => '',
    'Reset' => '',
    'Search' => '',
    'Select a form...' => '',
    'Start Tracking!' => '',
    'Status' => '',
    'The form tracking has been successfully created.' => '',
    'The form tracking has been successfully deleted.' => '',
    'The form tracking has been successfully updated.' => '',
    'The selected items have been successfully deleted.' => '',
    'The selected items have been successfully updated.' => '',
    'Tracking Domain' => '',
    'Tracking ID' => '',
    'Update' => '',
    'Update Form Tracking' => '',
    'Update Status' => '',
    'View' => '',
    'View Record' => '',
    'With this add-on, Google Analytics will be added directly to your form to track successful submissions and provide more insights on your form\'s performance.' => '',
];
