<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back up your database.' => 'Respaldar su base de datos.',
    'Backup your files.' => 'Respaldar sus archivos.',
    'Choose language' => 'Escoger idioma',
    'Congratulations, you have updated Easy Forms!' => 'Felicitaciones, ha actualizado Easy Forms!',
    'Continue' => 'Continuar',
    'Finished' => 'Terminado',
    'For security reasons, you must comment again the uncommented line in the "config/web.php" file.' => 'Por razones de seguridad, debe volver a comentar la linea descomentada del archivo "config/web.php".',
    'Go to Easy Forms' => 'Ir a Easy Forms',
    'If you have performed the next steps, you may proceed to update Easy Forms.' => 'Si ha realizado los siguientes pasos, puede proceder con la actualización de Easy Forms',
    'Install your new files in the right location, as described in the documentation.' => 'Instalar los archivos nuevos en la ubicación correcta, como se ha descrito en la documentación.',
    'Next Step' => 'Siguiente paso',
    'Note: If you have problems running your site, get in touch with our support team and we will be more than happy to help you.' => 'Nota: Si tiene problemas ejecutando su sitio, póngase en contacto con nuestro equipo de soporte que estaremos más que felices de atenderlo.',
    'Requirements' => 'Requermimientos',
    'Save and continue' => 'Guardar y continuar',
    'There was an error updating your database, please contact us.' => 'Hubo un error actualizando su base de datos, por favor contáctenos.',
    'Update app' => 'Actualizar aplicación',
    'Update to Easy Forms {version}' => 'Actualizar a Easy Forms {version}',
    'Updating Easy Forms' => 'Actualizando Easy Forms',
    'You have successfully updated your Easy Forms application.' => 'Usted ha actualizado exitósamente su aplicación.',
    'Your application was successfully updated!' => 'Su aplicación fue actualizada de forma exitosa!',
];
