<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reset' => '',
    'Search' => '',
    'Update Status' => '',
    'About this add-on' => '@@Acerca de este add-on@@',
    'Send form submission data to a specified URL when a form submission occurs' => '@@@@',
    'A WebHook is just a push notification from us to another server every time someone submits a form.' => 'Un webhook es una notificación push desde nuestro servidor a otro cada vez que se envía un formulario.',
    'Active' => 'Activo',
    'Add-ons' => 'Add-ons',
    'Are you sure you want to delete these webhooks? All data related to each item will be deleted. This action cannot be undone.' => '¿Está seguro que desea eliminar estos webhooks? Todos los datos relacionados con cada elemento serán eliminados. Esta acción no puede deshacerse.',
    'Are you sure you want to delete this webhook? All data related to this item will be deleted. This action cannot be undone.' => '¿Está seguro que desea eliminar este webhook? Todos los datos relacionados con este elemento serán eliminados. Esta acción no puede deshacerse.',
    'Create' => 'Crear',
    'Create Webhook' => 'Crear webhook',
    'Create a WebHook' => 'Crear un webhook',
    'Delete' => 'Eliminar',
    'Form' => 'Formulario',
    'Handshake Key' => 'Clave secreta',
    'ID' => 'ID',
    'Inactive' => 'Inactivo',
    'Json' => 'Json',
    'OFF' => 'OFF',
    'ON' => 'ON',
    'Page not found.' => 'Página no encontrada.',
    'Select a form...' => 'Seleccione un formulario...',
    'Send notifications to another server' => 'Envía notificaciones a otro servidor',
    'Status' => 'Estado',
    'The selected items have been successfully deleted.' => 'Los elementos seleccionados se han eliminado de forma exitosa.',
    'The selected items have been successfully updated.' => 'Los elementos seleccionados se han actualizado de forma exitosa.',
    'The webhook has been successfully created.' => 'El webhook se ha creado de forma exitosa.',
    'The webhook has been successfully deleted.' => 'El webhook se ha eliminado de forma exitosa.',
    'The webhook has been successfully updated.' => 'El webhook se ha actualizado de forma exitosa.',
    'Update' => 'Actualizar',
    'Update Webhook' => 'Actualizar webhook',
    'Url' => 'Url',
    'View Record' => 'Ver Registro',
    'Webhook' => 'Webhook',
    'Webhooks' => 'Webhooks',
    'Your handshake key' => 'Su clave secreta',
    'Your web hook url' => 'La url del web hook',
];
