<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Activo',
    'Add-ons' => 'Add-ons',
    'An invalid Add-on detected. Please verify your Add-On configuration.' => 'Un Add-on invalido ha sido detectado. Por favor, verifique la configuración de su Add-on.',
    'An invalid Add-on detected. Please verify your Add-ons directory.' => 'Un Add-on invalido ha sido detectado. Por favor, verifique el directorio de su Add-on.',
    'Are you sure you want to uninstall these add-ons? All data related to each item will be deleted. This action cannot be undone.' => '¿Está seguro que desea desinstalar estos add-ons? Todos los datos relacionados con cada elemento serán eliminados. Esta acción np puede deshacerse.',
    'Class' => 'Clase',
    'Class does not exist' => 'La clase no existe',
    'Description' => 'Descripción',
    'Extend and Expand the functionality of your forms' => 'Incremente y mejore la funcionalidad de sus formularios',
    'General' => 'General',
    'ID' => 'ID',
    'Inactive' => 'Inactivo',
    'Install' => 'Instalar',
    'Installed' => 'Instalado',
    'Name' => 'Nombre',
    'Page not found.' => 'Página no encontrada.',
    'Refresh' => 'Refrescar',
    'Status' => 'Estado',
    'The Add-ons list has been refreshed successfully.' => 'La lista de Add-ons ha sido refrescada de forma exitosa.',
    'The selected items have been installed successfully.' => 'Los elementos seleccionados han sido instalados de forma exitosa.',
    'The selected items have been uninstalled successfully.' => 'Los elementos seleccionados han sido desinstalados de forma exitosa.',
    'The selected items have been successfully updated.' => 'Los elementos seleccionados han sido actualizados de forma exitosa.',
    'Uninstall' => 'Desinstalar',
    'Update Status' => 'Actualizar sstado',
    'Use the “Refresh” button to see new Add-ons, after upload or delete add-on’s files.' => 'Use el botón "Refresh" para ver nuevos Add-ons, luego de subir o borrar los archivos del add-on.',
    'Version' => 'Versión',
];
