<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back up your database.' => 'Sichern Sie Ihre Datenbank.',
    'Backup your files.' => 'Sichern Sie Ihre Dateien.',
    'Choose language' => 'Wähle eine Sprache',
    'Congratulations, you have updated Easy Forms!' => 'Enhorabuena, ha mejorado las Formas fáciles!',
    'Continue' => 'Fortsetzen',
    'Finished' => 'Fertig',
    'For security reasons, you must comment again the uncommented line in the "config/web.php" file.' => 'Aus Sicherheitsgründen müssen Sie kommentieren erneut die Zeile in der "config/web.php" Datei.',
    'Go to Easy Forms' => 'Besuchen Easy Forms',
    'If you have performed the next steps, you may proceed to update Easy Forms.' => 'Wenn Sie die nächsten Schritte ausgeführt haben, können gehen Sie zu aktualisieren.',
    'Install your new files in the right location, as described in the documentation.' => 'Installieren Sie die neuen Dateien an der richtigen Stelle, wie in der Dokumentation beschrieben.',
    'Next Step' => 'Nächster Schritt',
    'Note: If you have problems running your site, get in touch with our support team and we will be more than happy to help you.' => 'Hinweis: Wenn Sie Probleme bei der Ausführung Ihrer Website haben, mit unserem Support-Team in Verbindung setzen und wir werden mehr als glücklich, Ihnen zu helfen.',
    'Requirements' => 'Bedarf',
    'Save and continue' => 'Speichern und fortfahren',
    'There was an error updating your database, please contact us.' => 'Es gab einen Fehler der Datenbank zu aktualisieren, kontaktieren Sie uns.',
    'Update app' => 'Update-App',
    'Update to Easy Forms {version}' => 'Update Easy Forms {version}',
    'Updating Easy Forms' => 'Aktualisierung Easy Forms',
    'You have successfully updated your Easy Forms application.' => 'Sie haben Ihre Anwendung erfolgreich aktualisiert.',
    'Your application was successfully updated!' => 'Ihre Bewerbung wurde erfolgreich aktualisiert!',
];
