<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Add-ons' => '',
    'An invalid Add-on detected. Please verify your Add-On configuration.' => '',
    'An invalid Add-on detected. Please verify your Add-ons directory.' => '',
    'Are you sure you want to uninstall these add-ons? All data related to each item will be deleted. This action cannot be undone.' => '',
    'Class' => '',
    'Class does not exist' => '',
    'Description' => '',
    'Extend and Expand the functionality of your forms' => '',
    'General' => '',
    'ID' => '',
    'Inactive' => '',
    'Install' => '',
    'Installed' => '',
    'Name' => '',
    'Page not found.' => '',
    'Refresh' => '',
    'Status' => '',
    'The Add-ons list has been refreshed successfully.' => '',
    'The selected items have been installed successfully.' => '',
    'The selected items have been successfully updated.' => '',
    'The selected items have been uninstalled successfully.' => '',
    'Uninstall' => '',
    'Update Status' => '',
    'Use the “Refresh” button to see new Add-ons, after upload or delete add-on’s files.' => '',
    'Version' => '',
];
