<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktiv',
    'Add-ons' => 'Erweiterungen',
    'An invalid Add-on detected. Please verify your Add-On configuration.' => 'Eine ungültige Erweiterung erkannt. Bitte überprüfen Sie Ihre Add-On-Konfiguration.',
    'An invalid Add-on detected. Please verify your Add-ons directory.' => 'Eine ungültige Erweiterung erkannt. Überprüfen Sie bitte Ihre Addons Verzeichnis.',
    'Are you sure you want to uninstall these add-ons? All data related to each item will be deleted. This action cannot be undone.' => 'Sind Sie sicher, dass Sie diese Add-ons deinstallieren? Alle Daten zu jedem Element bezogen werden gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    'Class' => 'Klasse',
    'Class does not exist' => 'Klasse ist nicht vorhanden',
    'Description' => 'Beschreibung',
    'Extend and Expand the functionality of your forms' => 'Verlängern und erweitern ihre die Funktionalität Ihrer Formulare',
    'General' => 'General',
    'ID' => 'ID',
    'Inactive' => 'Inaktiv',
    'Install' => 'Installieren',
    'Installed' => 'Wurde installiert',
    'Name' => 'Name',
    'Page not found.' => 'Seite nicht gefunden.',
    'Refresh' => 'Auffrischen',
    'Status' => 'Status',
    'The Add-ons list has been refreshed successfully.' => 'Das Add-ons-Liste wurde erfolgreich aktualisiert.',
    'The selected items have been installed successfully.' => 'Die ausgewählten Elemente wurden erfolgreich installiert.',
    'The selected items have been successfully updated.' => 'Die ausgewählten Elemente wurden erfolgreich aktualisiert.',
    'The selected items have been uninstalled successfully.' => 'Die ausgewählten Elemente wurden erfolgreich deinstalliert.',
    'Uninstall' => 'Deinstallieren',
    'Update Status' => 'Update Status',
    'Use the “Refresh” button to see new Add-ons, after upload or delete add-on’s files.' => '',
    'Version' => 'Version',
];
